import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { ThemeProvider } from '@/app/context/ThemeContext';
import { TodosProvider } from '@/app/context/TodosContext';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <TodosProvider>{children}</TodosProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
